#!/bin/bash

rsync -rt --delete --progress /home/fvdb/halde/  \
    /home/fvdb/zbigdata_mnt/\=BACKUP_HALDE\=

rsync -rt --delete --progress /home/fvdb/docs/ \
    /home/fvdb/zbigdata_mnt/\=BACKUP_DOKUMENTE\=


