#!/bin/bash
# tested on debian jessie...not unstable the bleeding edge

nodepids=$(ps aux | grep nodejs | grep -v grep | cut -c10-15)
echo $nodepids
for nodepid in ${nodepids[@]}
do
echo "Killing the hard way nodejs server with PID :"$nodepid
kill -9 $nodepid
done
echo "Done"


